### PR TITLE
Fix repeated calling of validator function

### LINKED ISSUE #94: First validate() call runs validator function twice
I have noticed this bug, that first `validate()` call runs all the validator functions twice.
Here is the simplest minimum reproducible example: https://codesandbox.io/p/sandbox/nice-fast-3vs9wy

I noticed because I started using async validators that call server and noticed double requests in the network.
My use case is that sometimes I need to create a form with initial values and immediately validate it.

### PR DESCRIPTION
**Pull request by nighca**
Fix #94 

In https://github.com/qiniu/formstate-x/pull/69 we merged `doValidation` & `applyValdiation`, so we can no longer decide if validation is triggered by checking `this.validation`

### CODE REVIEW

File: src/state.ts [hunk 1]
```diff
@@ -125,15 +125,13 @@ export abstract class ValidatableState<V> extends BaseState implements IState<V>
...
 
-    const validation = this.validation
-
-    action('activate-when-validate', () => {
-      this.activated = true
-    })()
-
-    // 若 `validation` 未发生变更，意味着未发生新的校验行为
-    // 若上边操作未触发自动的校验行为，强制调用之
-    if (this.validation === validation) {
```
Comment (lzfee0227) [inline src/state.ts:136]: 没这个之后代码好懂多了…

**Review by lzfee0227 — APPROVED** [review]
lgtm
